#define FenGen_FMDataDest

#undef write_old_resources_style

using System.Collections.Generic;
using System.IO;
using System.Text;
using AngelLoader.DataClasses;
using static AngelLoader.GameSupport;

// PERF_TODO: Notes for the writer:
// -Enum.ToString() is very expensive. Probably faster to do it manually with an if statement and nameof(value)
// -All the WriteLine()s take up a lot of time (most of which is GC). Using a StringBuilder would probably be
//  much faster.
// -The reader is lightning fast still. No need to do anything to it.

namespace AngelLoader.Ini
{
    internal static partial class Ini
    {
        // This method was autogenerated for maximum performance at runtime.
        internal static void ReadFMDataIni(string fileName, List<FanMission> fmsList)
        {
            var iniLines = File.ReadAllLines(fileName, Encoding.UTF8);

            if (fmsList.Count > 0) fmsList.Clear();

            bool fmsListIsEmpty = true;

            foreach (var line in iniLines)
            {
                var lineT = line.Trim();

                if (lineT.Length > 0 && lineT[0] == '[')
                {
                    if (lineT.Length >= 4 && lineT[1] == 'F' && lineT[2] == 'M' && lineT[3] == ']')
                    {
                        fmsList.Add(new FanMission());
                        if (fmsListIsEmpty) fmsListIsEmpty = false;
                    }

                    continue;
                }

                if (fmsListIsEmpty) continue;

                bool resourcesFound = false;

                // Comment chars (;) and blank lines will be rejected implicitly.
                // Since they're rare cases, checking for them would only slow us down.

                var fm = fmsList[fmsList.Count - 1];

                if (lineT.StartsWithFast_NoNullChecks("NoArchive="))
                {
                    var val = lineT.Substring(10);
                    fm.NoArchive = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("MarkedScanned="))
                {
                    var val = lineT.Substring(14);
                    fm.MarkedScanned = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("Archive="))
                {
                    var val = lineT.Substring(8);
                    fm.Archive = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("InstalledDir="))
                {
                    var val = lineT.Substring(13);
                    fm.InstalledDir = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("Title="))
                {
                    var val = lineT.Substring(6);
                    fm.Title = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("AltTitles="))
                {
                    var val = lineT.Substring(10);
                    if (!string.IsNullOrEmpty(val))
                    {
                        fm.AltTitles.Add(val);
                    }
                }
                else if (lineT.StartsWithFast_NoNullChecks("Author="))
                {
                    var val = lineT.Substring(7);
                    fm.Author = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("Game="))
                {
                    var val = lineT.Substring(5);
                    val = val.Trim();
                    if (val.EqualsI(nameof(Game.Thief1)))
                    {
                        fm.Game = Game.Thief1;
                    }
                    else if (val.EqualsI(nameof(Game.Thief2)))
                    {
                        fm.Game = Game.Thief2;
                    }
                    else if (val.EqualsI(nameof(Game.Thief3)))
                    {
                        fm.Game = Game.Thief3;
                    }
                    else if (val.EqualsI(nameof(Game.SS2)))
                    {
                        fm.Game = Game.SS2;
                    }
                    else if (val.EqualsI(nameof(Game.Unsupported)))
                    {
                        fm.Game = Game.Unsupported;
                    }
                    else
                    {
                        fm.Game = Game.Null;
                    }
                }
                else if (lineT.StartsWithFast_NoNullChecks("Installed="))
                {
                    var val = lineT.Substring(10);
                    fm.Installed = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("NoReadmes="))
                {
                    var val = lineT.Substring(10);
                    fm.NoReadmes = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("SelectedReadme="))
                {
                    var val = lineT.Substring(15);
                    fm.SelectedReadme = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("SizeBytes="))
                {
                    var val = lineT.Substring(10);
                    ulong.TryParse(val, out ulong result);
                    fm.SizeBytes = result;
                }
                else if (lineT.StartsWithFast_NoNullChecks("Rating="))
                {
                    var val = lineT.Substring(7);
                    bool success = int.TryParse(val, out int result);
                    fm.Rating = success ? result : -1;
                }
                else if (lineT.StartsWithFast_NoNullChecks("ReleaseDate="))
                {
                    var val = lineT.Substring(12);
                    fm.ReleaseDate.UnixDateString = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("LastPlayed="))
                {
                    var val = lineT.Substring(11);
                    fm.LastPlayed.UnixDateString = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("FinishedOn="))
                {
                    var val = lineT.Substring(11);
                    uint.TryParse(val, out uint result);
                    fm.FinishedOn = result;
                }
                else if (lineT.StartsWithFast_NoNullChecks("FinishedOnUnknown="))
                {
                    var val = lineT.Substring(18);
                    fm.FinishedOnUnknown = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("Comment="))
                {
                    var val = lineT.Substring(8);
                    fm.Comment = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("DisabledMods="))
                {
                    var val = lineT.Substring(13);
                    fm.DisabledMods = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("DisableAllMods="))
                {
                    var val = lineT.Substring(15);
                    fm.DisableAllMods = val.EqualsTrue();
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasResources="))
                {
                    var val = lineT.Substring(13);
                    fm.ResourcesScanned = !val.EqualsI("NotScanned");
                    FillFMHasXFields(fm, val);
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasMap="))
                {
                    var val = lineT.Substring(7);
                    fm.HasMap = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasAutomap="))
                {
                    var val = lineT.Substring(11);
                    fm.HasAutomap = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasScripts="))
                {
                    var val = lineT.Substring(11);
                    fm.HasScripts = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasTextures="))
                {
                    var val = lineT.Substring(12);
                    fm.HasTextures = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasSounds="))
                {
                    var val = lineT.Substring(10);
                    fm.HasSounds = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasObjects="))
                {
                    var val = lineT.Substring(11);
                    fm.HasObjects = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasCreatures="))
                {
                    var val = lineT.Substring(13);
                    fm.HasCreatures = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasMotions="))
                {
                    var val = lineT.Substring(11);
                    fm.HasMotions = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasMovies="))
                {
                    var val = lineT.Substring(10);
                    fm.HasMovies = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("HasSubtitles="))
                {
                    var val = lineT.Substring(13);
                    fm.HasSubtitles = val.EqualsTrue();
                    resourcesFound = true;
                }
                else if (lineT.StartsWithFast_NoNullChecks("LanguagesString="))
                {
                    var val = lineT.Substring(16);
                    fm.LanguagesString = val;
                }
                else if (lineT.StartsWithFast_NoNullChecks("TagsString="))
                {
                    var val = lineT.Substring(11);
                    fm.TagsString = val;
                }
                if (resourcesFound) fm.ResourcesScanned = true;
            }
        }

        // This method was autogenerated for maximum performance at runtime.
        internal static void WriteFMDataIni(List<FanMission> fmDataList, string fileName)
        {
            // Averaged over the 1573 FMs in my FMData.ini file (in new HasResources format)
            const int averageFMEntryCharCount = 378;
            var sb = new StringBuilder(averageFMEntryCharCount * fmDataList.Count);

            foreach (var fm in fmDataList)
            {
                sb.AppendLine("[FM]");

                if (fm.NoArchive)
                {
                    sb.Append("NoArchive=");
                    sb.AppendLine(fm.NoArchive.ToString());
                }
                if (fm.MarkedScanned)
                {
                    sb.Append("MarkedScanned=");
                    sb.AppendLine(fm.MarkedScanned.ToString());
                }
                if (!string.IsNullOrEmpty(fm.Archive))
                {
                    sb.Append("Archive=");
                    sb.AppendLine(fm.Archive);
                }
                if (!string.IsNullOrEmpty(fm.InstalledDir))
                {
                    sb.Append("InstalledDir=");
                    sb.AppendLine(fm.InstalledDir);
                }
                if (!string.IsNullOrEmpty(fm.Title))
                {
                    sb.Append("Title=");
                    sb.AppendLine(fm.Title);
                }
                foreach (var s in fm.AltTitles)
                {
                    sb.Append("AltTitles=");
                    sb.AppendLine(s);
                }
                if (!string.IsNullOrEmpty(fm.Author))
                {
                    sb.Append("Author=");
                    sb.AppendLine(fm.Author);
                }
                // Don't write Game.Null
                // Much faster to do this than Enum.ToString()
                if (fm.Game == Game.Thief1)
                {
                    sb.AppendLine("Game=Thief1");
                }
                else if (fm.Game == Game.Thief2)
                {
                    sb.AppendLine("Game=Thief2");
                }
                else if (fm.Game == Game.Thief3)
                {
                    sb.AppendLine("Game=Thief3");
                }
                else if (fm.Game == Game.SS2)
                {
                    sb.AppendLine("Game=SS2");
                }
                else if (fm.Game == Game.Unsupported)
                {
                    sb.AppendLine("Game=Unsupported");
                }
                if (fm.Installed)
                {
                    sb.Append("Installed=");
                    sb.AppendLine(fm.Installed.ToString());
                }
                if (fm.NoReadmes)
                {
                    sb.Append("NoReadmes=");
                    sb.AppendLine(fm.NoReadmes.ToString());
                }
                if (!string.IsNullOrEmpty(fm.SelectedReadme))
                {
                    sb.Append("SelectedReadme=");
                    sb.AppendLine(fm.SelectedReadme);
                }
                if (fm.SizeBytes != 0)
                {
                    sb.Append("SizeBytes=");
                    sb.AppendLine(fm.SizeBytes.ToString());
                }
                if (fm.Rating != -1)
                {
                    sb.Append("Rating=");
                    sb.AppendLine(fm.Rating.ToString());
                }
                if (!string.IsNullOrEmpty(fm.ReleaseDate.UnixDateString))
                {
                    sb.Append("ReleaseDate=");
                    sb.AppendLine(fm.ReleaseDate.UnixDateString);
                }
                if (!string.IsNullOrEmpty(fm.LastPlayed.UnixDateString))
                {
                    sb.Append("LastPlayed=");
                    sb.AppendLine(fm.LastPlayed.UnixDateString);
                }
                // NOTE: This is not in itself an enum, it's a uint, so it's fast. We just cast it to an enum
                // later on, but no worries here.
                if (fm.FinishedOn != 0)
                {
                    sb.Append("FinishedOn=");
                    sb.AppendLine(fm.FinishedOn.ToString());
                }
                if (fm.FinishedOnUnknown)
                {
                    sb.Append("FinishedOnUnknown=");
                    sb.AppendLine(fm.FinishedOnUnknown.ToString());
                }
                if (!string.IsNullOrEmpty(fm.Comment))
                {
                    sb.Append("Comment=");
                    sb.AppendLine(fm.Comment);
                }
                if (!string.IsNullOrEmpty(fm.DisabledMods))
                {
                    sb.Append("DisabledMods=");
                    sb.AppendLine(fm.DisabledMods);
                }
                if (fm.DisableAllMods)
                {
                    sb.Append("DisableAllMods=");
                    sb.AppendLine(fm.DisableAllMods.ToString());
                }
#if write_old_resources_style
                if (fm.ResourcesScanned)
                {
                    {
                        sb.AppendLine("HasMap=" + fm.HasMap.ToString());
                    }
                    {
                        sb.AppendLine("HasAutomap=" + fm.HasAutomap.ToString());
                    }
                    {
                        sb.AppendLine("HasScripts=" + fm.HasScripts.ToString());
                    }
                    {
                        sb.AppendLine("HasTextures=" + fm.HasTextures.ToString());
                    }
                    {
                        sb.AppendLine("HasSounds=" + fm.HasSounds.ToString());
                    }
                    {
                        sb.AppendLine("HasObjects=" + fm.HasObjects.ToString());
                    }
                    {
                        sb.AppendLine("HasCreatures=" + fm.HasCreatures.ToString());
                    }
                    {
                        sb.AppendLine("HasMotions=" + fm.HasMotions.ToString());
                    }
                    {
                        sb.AppendLine("HasMovies=" + fm.HasMovies.ToString());
                    }
                    {
                        sb.AppendLine("HasSubtitles=" + fm.HasSubtitles.ToString());
                    }
                }
#else
                sb.Append("HasResources=");
                if (fm.ResourcesScanned)
                {
                    CommaCombineHasXFields(fm, sb);
                }
                else
                {
                    sb.AppendLine("NotScanned");
                }
#endif
                if (!string.IsNullOrEmpty(fm.LanguagesString))
                {
                    sb.Append("LanguagesString=");
                    sb.AppendLine(fm.LanguagesString);
                }
                if (!string.IsNullOrEmpty(fm.TagsString))
                {
                    sb.Append("TagsString=");
                    sb.AppendLine(fm.TagsString);
                }
            }

            using var sw = new StreamWriter(fileName, false, Encoding.UTF8);
            sw.Write(sb.ToString());
        }
    }
}
