#define FenGen_LanguageSupportDest

using static AL_Common.Common;
using static AngelLoader.FenGenAttributes;

namespace AngelLoader
{
    [FenGenLanguageSupportDestClass]
    public static partial class LanguageSupport
    {
        #region Autogenerated language support code

        public enum LanguageIndex : uint
        {
            English,
            Czech,
            Dutch,
            French,
            German,
            Hungarian,
            Italian,
            Japanese,
            Polish,
            Russian,
            Spanish
        }

        public static HashSetI LangsHash = new HashSetI(11)
        {
            "english",
            "czech",
            "dutch",
            "french",
            "german",
            "hungarian",
            "italian",
            "japanese",
            "polish",
            "russian",
            "spanish"
        };

        public static DictionaryI<LanguageIndex> LangStringsToEnums = new(11)
        {
            { "english", LanguageIndex.English },
            { "czech", LanguageIndex.Czech },
            { "dutch", LanguageIndex.Dutch },
            { "french", LanguageIndex.French },
            { "german", LanguageIndex.German },
            { "hungarian", LanguageIndex.Hungarian },
            { "italian", LanguageIndex.Italian },
            { "japanese", LanguageIndex.Japanese },
            { "polish", LanguageIndex.Polish },
            { "russian", LanguageIndex.Russian },
            { "spanish", LanguageIndex.Spanish }
        };

        public static DictionaryI<string[]> LangCodes = new DictionaryI<string[]>(11)
        {
            { "english", new[] { "en" } },
            { "czech", new[] { "cz" } },
            { "dutch", new[] { "nl" } },
            { "french", new[] { "fr" } },
            { "german", new[] { "de" } },
            { "hungarian", new[] { "hu" } },
            { "italian", new[] { "it" } },
            { "japanese", new[] { "ja", "jp" } },
            { "polish", new[] { "pl" } },
            { "russian", new[] { "ru" } },
            { "spanish", new[] { "es" } }
        };

        public static DictionaryI<string> LangTranslatedNames = new DictionaryI<string>(11)
        {
            { "english", "English" },
            { "czech", "Čeština" },
            { "dutch", "Nederlands" },
            { "french", "Français" },
            { "german", "Deutsch" },
            { "hungarian", "Magyar" },
            { "italian", "Italiano" },
            { "japanese", "日本語" },
            { "polish", "Polski" },
            { "russian", "Русский" },
            { "spanish", "Español" }
        };

        #endregion
    }
}
