<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Product>Pfim</Product>
    <Description>A simple and fast .NET Standard image decoder for targa (.tga) and direct draw surface (.dds) images</Description>
    <Copyright>Nick Babcock</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>Nick Babcock</Authors>

    <Major>0</Major>
    <Minor>11</Minor>
    <Revision>4</Revision>
    <AssemblyVersion>$(Major).$(Minor).$(Revision)</AssemblyVersion>
    <AssemblyFileVersion>$(Major).$(Minor).$(Revision)</AssemblyFileVersion>
    <InformationalVersion>$(Major).$(Minor).$(Revision)</InformationalVersion>
    <Version>$(Major).$(Minor).$(Revision)</Version>
    <FileVersion>$(Major).$(Minor).$(Revision)</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
</Project>
