using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FenGen
{
    internal static class CommonStatic
    {
        internal const string AutogeneratedMessage =
            @"// This method was autogenerated for maximum performance at runtime.";

        internal const string TopCodeMessage = @"// This supporting code was autogenerated.";

        internal static readonly string[] Prefixes = { "private", "internal", "protected", "public", "static", "readonly", "dynamic" };

        internal static string StripPrefixes(string line)
        {
            while (Prefixes.Any(x => line.StartsWithI(x + ' ')))
            {
                foreach (var pre in Prefixes)
                {
                    if (line.StartsWithI(pre + ' '))
                    {
                        line = line.Substring(pre.Length + 1).TrimStart();
                    }
                }
            }
            return line;
        }
    }
}
